version: "2.4"

volumes:
  database:
    name: btc-db
  blockchain:
    name: btc-data
  database1:
    name: angor-db

services:

  indexer:
    container_name: tbtc-indexer
    image: blockcore/indexer-angor:0.2.65
    mem_limit: 2048m
    cpus: 0.200
    environment:
      VIRTUAL_HOST: tbtc.indexer.angor.io
      VIRTUAL_PORT: 9910
      VIRTUAL_PROTO: http
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: tbtc.indexer.angor.io
      LETSENCRYPT_EMAIL: admin@blockcore.net
      ASPNETCORE_URLS: http://+:9910
    command: ["--chain=TBTC","--Network:RPCPort=38332"] # override rpcport in signet its 38332
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
      chain:
        condition: service_healthy
     #ports:
     # - 9910:9910 # Make this a public node.
    networks:
      - btcnetwork
      - proxy

  chain:
    container_name: tbtc-chain
    #image: blockcore/bitcoin-signet:latest
    build: .
    mem_limit: 2048m
    cpus: 0.8 # how many cpus to use
    healthcheck:
      test: ["CMD", "bitcoin-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    restart: unless-stopped
    stop_grace_period: 15m
    volumes:
      - blockchain:/root/.bitcoin
    environment:
      UACOMMENT: $UACOMMENT
      BLOCKPRODUCTIONDELAY: ${BLOCKPRODUCTIONDELAY:-30}
      MINERENABLED: ${MINERENABLED:-0} # change this to 1 if this node needs to mine (however for simplicity there should only be one mining node per challenge)
      NBITS: $NBITS
      MINETO: ${MINETO:-tb1qk4pq0rh75qtph47wlufhyss43flhvhvwe4zt8a}
      PRIVKEY: ${PRIVKEY:-cRz3Ci2aUNmdP4pViSM8LafwKHZmvn4X6gjeCXzVkBYBLhzA3uFC} # private key path is m/84'/1'/0'/0/0 of test wallet mnemonic "margin radio diamond leg loud street announce guitar video shiver speed eyebrow"
      SIGNETCHALLENGE: ${SIGNETCHALLENGE:-512102b57c4413a0354bcc360a37e035f26670deda14bab613c28fbd30fe52b2deccc151ae}
      EXTERNAL_IP: $EXTERNAL_IP
      RPCUSER: ${RPCUSER:-rpcuser}
      RPCPASSWORD: ${RPCPASSWORD:-rpcpassword}
    ports:
      - 18333:18333 # Make this a public node.
      - 8333:8333 # Make this a public node.
      - 38333:38333 # Make this a public node.
      - 38332:38332
    networks:
      - btcnetwork

  mongo:
    container_name: tbtc-mongo
    image: mongo:5.0.12
    mem_limit: 2048m
    cpus: 0.200

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

    restart: unless-stopped
    stop_grace_period: 5m
    volumes:
      - database:/data/db
      - database:/data/configdb
    #ports:
    #  - 27017:27017 # Make this a public node.
    networks:
      - btcnetwork
      
  explorer:
    container_name: explorer
    image: blockcore/explorer:0.2.28
    mem_limit: 256m
    cpus: 0.200
    environment:
      VIRTUAL_HOST: explorer.angor.io
      VIRTUAL_PORT: 9911
      VIRTUAL_NETWORK: proxy
      VIRTUAL_PROTO: http
      LETSENCRYPT_HOST: explorer.angor.io
      LETSENCRYPT_EMAIL: admin@blockcore.net
      ASPNETCORE_URLS: http://+:9910
    command: ["--chain=TBTC"]
    restart: unless-stopped
    #ports:
    #  - 9911:9911 # Make this a public node.
    networks:
      - proxy
      - btcnetwork

  blockcore-angor:
    container_name: angor
    image: blockcore/angor:0.0.24
    mem_limit: 1024m
    cpus: 0.200
    environment:
      VIRTUAL_HOST: test.angor.io
      VIRTUAL_PORT: 5500
      VIRTUAL_PROTO: http
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: test.angor.io
      LETSENCRYPT_EMAIL: admin@blockcore.net
      ASPNETCORE_URLS: http://+:5500
      Logging__LogLevel__Default: Debug
      DataConfig__UseDefaultPath: "true"
    restart: unless-stopped
    #ports:
    #  - 5500:5500
    volumes:
      - database1:/root/.aspnet
    networks:
      - proxy

  strfry-relay:
    container_name: strfry-relay
    image: dockurr/strfry:latest
    environment:
      VIRTUAL_HOST: relay.angor.io
      VIRTUAL_PORT: 7777
      VIRTUAL_PROTO: http
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: relay.angor.io
      LETSENCRYPT_EMAIL: admin@blockcore.net
    #ports:
    #  - 7777:7777
    volumes:
      - ./strfry/:/app/strfry-db
      - ./strfry/strfry.conf:/etc/strfry.conf
    networks:
      - proxy

  web:
    image: getumbrel/umbrel-nostr-relay
    user: "1000:1000"
    container_name: public-relay-web
    restart: on-failure
    environment:
      RELAY_HOST: "strfry-relay"
      RELAY_PORT: "7777"
    ports:
      - 3000:3000 # to access the web view use relay.angor.io:3000
    networks:
      - proxy

  strfry-relay-2:
    container_name: strfry-relay-2
    image: dockurr/strfry:latest
    environment:
      VIRTUAL_HOST: relay2.angor.io
      VIRTUAL_PORT: 7778
      VIRTUAL_PROTO: http
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: relay2.angor.io
      LETSENCRYPT_EMAIL: admin@blockcore.net
    #ports:
    #  - 7777:7777
    volumes:
      - ./strfry2/:/app/strfry-db
      - ./strfry2/strfry.conf:/etc/strfry.conf
    networks:
      - proxy

  web2:
    image: getumbrel/umbrel-nostr-relay
    user: "1000:1000"
    container_name: public-relay-web-2
    restart: on-failure
    environment:
      RELAY_HOST: "strfry-relay-2"
      RELAY_PORT: "7778"
    ports:
      - 3001:3001 # to access the web view use relay.angor.io:3000
    networks:
      - proxy

networks:
  btcnetwork:
    external: false
    name: btcnetwork
  proxy:
    external: true
    name: proxy
